import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;

public class Main {
    static DataStore data; static JFrame frame; static final String ADMIN_USER="admin", ADMIN_PASS="admin01";
    static Font normal=new Font("SansSerif",Font.PLAIN,14), title=new Font("SansSerif",Font.BOLD,22);
    public static void main(String[] args){SwingUtilities.invokeLater(()->{data=DataStore.load(); UIManager.put("OptionPane.messageFont",normal); showHome();});}
    static void base(String t){frame=new JFrame(t);frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);frame.setSize(900,650);frame.setLocationRelativeTo(null);}
    static JPanel panel(){JPanel p=new JPanel(new GridBagLayout());p.setBorder(BorderFactory.createEmptyBorder(18,18,18,18));return p;}
    static JButton btn(String s){JButton b=new JButton(s);b.setFont(normal);return b;} static JLabel label(String s){JLabel l=new JLabel(s);l.setFont(normal);return l;}
    static void showHome(){base("Course Registration System");JPanel p=panel();addTitle(p,"Course Registration System",0); JButton a=btn("Admin Login"),s=btn("Student Login"),x=btn("Exit"); addRow(p,a,1);addRow(p,s,2);addRow(p,x,3);a.addActionListener(e->adminLogin());s.addActionListener(e->studentLogin());x.addActionListener(e->System.exit(0));frame.setContentPane(p);frame.setVisible(true);}
    static void addTitle(JPanel p,String t,int r){GridBagConstraints g=g(r);g.gridwidth=2;p.add(new JLabel(t){ {setFont(title);} },g);} static GridBagConstraints g(int r){GridBagConstraints g=new GridBagConstraints();g.gridx=0;g.gridy=r;g.insets=new Insets(8,8,8,8);g.fill=GridBagConstraints.HORIZONTAL;return g;} static void addRow(JPanel p,JComponent c,int r){GridBagConstraints q=g(r);q.gridx=0;q.gridwidth=2;p.add(c,q);}
    static String ask(String m){return JOptionPane.showInputDialog(frame,m);} static void msg(String m){JOptionPane.showMessageDialog(frame,m);} static boolean confirm(String m){return JOptionPane.showConfirmDialog(frame,m,"Confirm",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION;}
    static void adminLogin(){JTextField u=new JTextField();JPasswordField pw=new JPasswordField();JPanel p=new JPanel(new GridLayout(2,2,8,8));p.add(label("Username"));p.add(u);p.add(label("Password"));p.add(pw);if(JOptionPane.showConfirmDialog(frame,p,"Admin Login",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){if(ADMIN_USER.equals(u.getText().trim())&&ADMIN_PASS.equals(new String(pw.getPassword())))adminPortal();else msg("Invalid admin credentials.");}}
    static void studentLogin(){JComboBox<String> pr=new JComboBox<>();for(Programme p:data.programmes())pr.addItem(p.getName());JTextField u=new JTextField();JPasswordField pw=new JPasswordField();JPanel p=new JPanel(new GridLayout(3,2,8,8));p.add(label("Programme"));p.add(pr);p.add(label("Username"));p.add(u);p.add(label("Password"));p.add(pw);if(JOptionPane.showConfirmDialog(frame,p,"Student Login",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){Student s=data.findUsername(u.getText().trim());if(s==null){msg("Invalid username or password.");return;}if(!s.getProgramme().equals(pr.getSelectedItem())){msg("Selected programme does not match this username.");return;}if(!s.verifyPassword(new String(pw.getPassword()))){msg("Invalid username or password.");return;}studentPortal(s);}}
    static void adminPortal(){base("Admin Portal");JPanel p=panel();addTitle(p,"Admin Portal",0);String[] names={"Programmes","Students","Courses","Exit"};for(int i=0;i<names.length;i++){JButton b=btn(names[i]);addRow(p,b,i+1);final int k=i;b.addActionListener(e->{if(k==0)programmeMenu();else if(k==1)studentMenu();else if(k==2)courseMenu();else showHome();});}frame.setContentPane(p);frame.setVisible(true);}
    static void programmeMenu(){String[] o={"Add Programme","Edit Programme","Delete Programme","View Programmes"};String c=(String)JOptionPane.showInputDialog(frame,"Choose an action","Programme Management",JOptionPane.PLAIN_MESSAGE,null,o,o[0]);if(c==null)return;switch(c){case "Add Programme":addProgramme();break;case "Edit Programme":editProgramme();break;case "Delete Programme":deleteProgramme();break;default:viewProgrammes();}}
    static void addProgramme(){JTextField n=new JTextField();if(JOptionPane.showConfirmDialog(frame,n,"Programme name",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){String v=n.getText().trim();if(v.isEmpty())return;if(data.findProgramme(v)!=null){msg("Programme already exists. Please choose another.");return;}data.programmes().add(new Programme(v));data.save();}}
    static void editProgramme(){Programme p=chooseProgramme("Edit programme");if(p==null)return;String v=ask("New programme name:");if(v==null)return;v=v.trim();if(v.isEmpty())return;Programme other=data.findProgramme(v);if(other!=null&&other!=p){msg("Programme already exists. Please choose another.");return;}String old=p.getName();p.setName(v);for(Student s:data.students())if(s.getProgramme().equals(old))s.setProgramme(v);for(Course c:data.courses())if(c.getProgramme().equals(old))c.setProgramme(v);data.save();}
    static void deleteProgramme(){Programme p=chooseProgramme("Delete programme");if(p==null)return;for(Student s:data.students())if(s.getProgramme().equals(p.getName())){msg("Cannot delete this programme while students are assigned to it.");return;}if(confirm("Delete programme "+p.getName()+"? Courses under it will also be deleted.")){data.courses().removeIf(c->c.getProgramme().equals(p.getName())&&!c.isDefaultCourse());data.programmes().remove(p);data.save();}}
    static void viewProgrammes(){StringBuilder b=new StringBuilder();for(Programme p:data.programmes())b.append("• ").append(p.getName()).append("\n");showText("Programmes",b.toString());}
    static Programme chooseProgramme(String title){return (Programme)JOptionPane.showInputDialog(frame,title,"Programme",JOptionPane.PLAIN_MESSAGE,null,data.programmes().toArray(),data.programmes().get(0));}
    static void studentMenu(){String[] o={"Add Student","Edit Student","Delete Student","Reset Student Password","View Students"};String c=(String)JOptionPane.showInputDialog(frame,"Choose an action","Student Management",JOptionPane.PLAIN_MESSAGE,null,o,o[0]);if(c==null)return;switch(c){case "Add Student":addStudent();break;case "Edit Student":editStudent();break;case "Delete Student":deleteStudent();break;case "Reset Student Password":resetPassword();break;default:viewStudents();}}
    static JPanel studentFields(Student s,boolean password,JLabel idWarn,JLabel userWarn,JTextField id,JTextField first,JTextField last,JTextField user,JComboBox<String> prog,JPasswordField pw){JPanel p=new JPanel(new GridLayout(password?6:5,2,8,4));p.add(label("Student ID *"));p.add(id);p.add(new JLabel());p.add(idWarn);p.add(label("First Name *"));p.add(first);p.add(label("Last Name *"));p.add(last);p.add(label("Username *"));p.add(user);p.add(new JLabel());p.add(userWarn);p.add(label("Programme *"));p.add(prog);if(password){p.add(label("Password *"));p.add(pw);}return p;}
    static void addStudent(){JTextField id=new JTextField(),first=new JTextField(),last=new JTextField(),user=new JTextField();JPasswordField pw=new JPasswordField();JComboBox<String> pr=new JComboBox<>();for(Programme p:data.programmes())pr.addItem(p.getName());JLabel iw=label(" "),uw=label(" ");DocumentListener dl=new DocumentListener(){public void insertUpdate(DocumentEvent e){v();}public void removeUpdate(DocumentEvent e){v();}public void changedUpdate(DocumentEvent e){v();}void v(){String i=id.getText().trim(),u=user.getText().trim();iw.setText(i.isEmpty()?" ":data.findStudentId(i)!=null?"⚠ Student ID already exists. Please choose another.":"✓ Student ID is available.");uw.setText(u.isEmpty()?" ":data.findUsername(u)!=null?"⚠ Username already exists. Please choose another.":"✓ Username is available.");}};id.getDocument().addDocumentListener(dl);user.getDocument().addDocumentListener(dl);if(JOptionPane.showConfirmDialog(frame,studentFields(null,true,iw,uw,id,first,last,user,pr,pw),"Create Student",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){String i=id.getText().trim(),u=user.getText().trim();if(i.isEmpty()||u.isEmpty()||first.getText().trim().isEmpty()||last.getText().trim().isEmpty()||new String(pw.getPassword()).isEmpty()){msg("Please fill all required fields.");return;}if(data.findStudentId(i)!=null){msg("Student ID already exists. Please choose another.");return;}if(data.findUsername(u)!=null){msg("Username already exists. Please choose another.");return;}Student s=new Student(i,first.getText().trim(),last.getText().trim(),u,new String(pw.getPassword()),(String)pr.getSelectedItem());data.students().add(s);data.save();}}
    static Student chooseStudent(String t){return (Student)JOptionPane.showInputDialog(frame,t,"Student",JOptionPane.PLAIN_MESSAGE,null,data.students().toArray(),data.students().isEmpty()?null:data.students().get(0));}
    static void editStudent(){Student s=chooseStudent("Edit student");if(s==null)return;JTextField id=new JTextField(s.getStudentId()),first=new JTextField(s.getFirstName()),last=new JTextField(s.getLastName()),user=new JTextField(s.getUsername());JComboBox<String> pr=new JComboBox<>();for(Programme p:data.programmes())pr.addItem(p.getName());pr.setSelectedItem(s.getProgramme());JLabel iw=label(" "),uw=label(" ");DocumentListener dl=new DocumentListener(){public void insertUpdate(DocumentEvent e){v();}public void removeUpdate(DocumentEvent e){v();}public void changedUpdate(DocumentEvent e){v();}void v(){Student x=data.findStudentId(id.getText().trim());iw.setText(x!=null&&x!=s?"⚠ Student ID already exists. Please choose another.":" ");Student y=data.findUsername(user.getText().trim());uw.setText(y!=null&&y!=s?"⚠ Username already exists. Please choose another.":" ");}};id.getDocument().addDocumentListener(dl);user.getDocument().addDocumentListener(dl);if(JOptionPane.showConfirmDialog(frame,studentFields(s,false,iw,uw,id,first,last,user,pr,null),"Edit Student",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){Student x=data.findStudentId(id.getText().trim()),y=data.findUsername(user.getText().trim());if((x!=null&&x!=s)||(y!=null&&y!=s)){msg("Student ID or username already exists. Please choose another.");return;}s.setStudentId(id.getText().trim());s.setFirstName(first.getText().trim());s.setLastName(last.getText().trim());s.setUsername(user.getText().trim());s.setProgramme((String)pr.getSelectedItem());data.save();}}
    static void deleteStudent(){Student s=chooseStudent("Delete student");if(s!=null&&confirm("Delete "+s.getFullName()+"?")){for(Course c:data.courses())c.withdraw(s.getUsername());data.students().remove(s);data.save();}}
    static void resetPassword(){Student s=chooseStudent("Reset password (existing password is never shown)");if(s==null)return;JPasswordField a=new JPasswordField(),b=new JPasswordField();JPanel p=new JPanel(new GridLayout(2,2,8,8));p.add(label("New password"));p.add(a);p.add(label("Confirm password"));p.add(b);if(JOptionPane.showConfirmDialog(frame,p,"Reset Password",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){String x=new String(a.getPassword()),y=new String(b.getPassword());if(x.isEmpty()||!x.equals(y)){msg("Passwords do not match.");return;}s.setPassword(x);data.save();msg("Password updated. The existing password cannot be viewed.");}}
    static void viewStudents(){StringBuilder b=new StringBuilder();for(Student s:data.students())b.append(s).append("\n");showText("Students",b.toString());}
    static void courseMenu(){Programme p=chooseProgramme("Select programme for course management");if(p==null)return;String[] o={"Add Course","Edit Course","Delete Course","View Courses"};String c=(String)JOptionPane.showInputDialog(frame,"Courses for: "+p.getName(),"Course Management",JOptionPane.PLAIN_MESSAGE,null,o,o[0]);if(c==null)return;switch(c){case "Add Course":createCourse(p);break;case "Edit Course":editCourse(p);break;case "Delete Course":deleteCourse(p);break;default:viewCourses(p);}}
    static void createCourse(Programme p){JTextField name=new JTextField(),id=new JTextField(),max=new JTextField("30"),ins=new JTextField(),sec=new JTextField("1"),loc=new JTextField();JPanel q=new JPanel(new GridLayout(6,2,8,8));String[] l={"Course Name","Course ID","Maximum Students","Instructor","Section","Location"};JTextField[] f={name,id,max,ins,sec,loc};for(int i=0;i<6;i++){q.add(label(l[i]));q.add(f[i]);}if(JOptionPane.showConfirmDialog(frame,q,"Create Course — "+p.getName(),JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){if(data.findCourse(id.getText().trim())!=null){msg("Course ID already exists. Please choose another.");return;}try{data.courses().add(new Course(name.getText().trim(),id.getText().trim(),Integer.parseInt(max.getText().trim()),ins.getText().trim(),Integer.parseInt(sec.getText().trim()),loc.getText().trim(),p.getName(),false));data.save();}catch(Exception e){msg("Maximum students and section must be valid numbers.");}}}
    static List<Course> coursesFor(Programme p){List<Course> r=new ArrayList<>();for(Course c:data.courses())if(c.getProgramme().equals(p.getName()))r.add(c);return r;}
    static Course chooseCourse(String t,Programme p){List<Course> cs=coursesFor(p);return (Course)JOptionPane.showInputDialog(frame,t,"Course",JOptionPane.PLAIN_MESSAGE,null,cs.toArray(),cs.isEmpty()?null:cs.get(0));}
    static void editCourse(Programme p){Course c=chooseCourse("Edit course",p);if(c==null)return;JTextField name=new JTextField(c.getCourseName()),id=new JTextField(c.getCourseID()),max=new JTextField(""+c.getMaxStudents()),ins=new JTextField(c.getInstructorName()),sec=new JTextField(""+c.getCourseSection()),loc=new JTextField(c.getCourseLocation());JPanel q=new JPanel(new GridLayout(6,2,8,8));String[] l={"Course Name","Course ID","Maximum Students","Instructor","Section","Location"};JTextField[] f={name,id,max,ins,sec,loc};for(int i=0;i<6;i++){q.add(label(l[i]));q.add(f[i]);}if(JOptionPane.showConfirmDialog(frame,q,"Edit Course — "+p.getName(),JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){Course o=data.findCourse(id.getText().trim());if(o!=null&&o!=c){msg("Course ID already exists. Please choose another.");return;}try{if(Integer.parseInt(max.getText().trim())<c.getCurrentStudents()){msg("Maximum students cannot be below current registrations.");return;}String oldId=c.getCourseID(); c.setCourseName(name.getText().trim());c.setCourseID(id.getText().trim());c.setMaxStudents(Integer.parseInt(max.getText().trim()));c.setInstructorName(ins.getText().trim());c.setCourseSection(Integer.parseInt(sec.getText().trim()));c.setCourseLocation(loc.getText().trim()); if(!oldId.equalsIgnoreCase(c.getCourseID())) for(Student st:data.students()) if(st.getRegisteredCourses().remove(oldId)) st.getRegisteredCourses().add(c.getCourseID()); data.save();}catch(Exception e){msg("Maximum students and section must be valid numbers.");}}}
    static void deleteCourse(Programme p){Course c=chooseCourse("Delete course",p);if(c==null)return;if(c.isDefaultCourse()){msg("This is a protected default course and cannot be deleted.");return;}if(confirm("Delete "+c.getCourseName()+"?")){for(Student s:data.students())s.getRegisteredCourses().remove(c.getCourseID());data.courses().remove(c);data.save();}}
    static void viewCourses(Programme p){StringBuilder b=new StringBuilder();for(Course c:coursesFor(p))b.append(c.getCourseID()).append(" - ").append(c.getCourseName()).append(" | Capacity ").append(c.getCurrentStudents()).append("/").append(c.getMaxStudents()).append(" | Instructor: ").append(c.getInstructorName()).append("\n");showText("Courses — "+p.getName(),b.toString());}
    static void studentPortal(Student s){base("Student Portal — "+s.getFullName());JPanel p=panel();addTitle(p,"Student Portal",0);JButton a=btn("Available Courses"),b=btn("My Courses"),c=btn("Register Course"),d=btn("Withdraw Course"),e=btn("Account Settings"),x=btn("Logout");addRow(p,a,1);addRow(p,b,2);addRow(p,c,3);addRow(p,d,4);addRow(p,e,5);addRow(p,x,6);a.addActionListener(z->availableCourses(s));b.addActionListener(z->myCourses(s));c.addActionListener(z->registerCourse(s));d.addActionListener(z->withdrawCourse(s));e.addActionListener(z->accountSettings(s));x.addActionListener(z->showHome());frame.setContentPane(p);frame.setVisible(true);}
    static void availableCourses(Student s){StringBuilder b=new StringBuilder();for(Course c:data.courses())if(c.getProgramme().equals(s.getProgramme()))b.append(c.getCourseID()).append(" - ").append(c.getCourseName()).append(" ("+c.getCurrentStudents()+"/"+c.getMaxStudents()+")\n");showText("Available Courses",b.toString());}
    static Course chooseStudentCourse(Student s,String t){List<Course> cs=new ArrayList<>();for(Course c:data.courses())if(c.getProgramme().equals(s.getProgramme()))cs.add(c);return (Course)JOptionPane.showInputDialog(frame,t,"Course",JOptionPane.PLAIN_MESSAGE,null,cs.toArray(),cs.isEmpty()?null:cs.get(0));}
    static void registerCourse(Student s){Course c=chooseStudentCourse(s,"Select course to register");if(c==null)return;if(c.register(s.getUsername())){s.getRegisteredCourses().add(c.getCourseID());data.save();msg("Registered successfully.");}else msg("Registration failed. The course may be full or you may already be registered.");}
    static void withdrawCourse(Student s){Course c=chooseStudentCourse(s,"Select course to withdraw");if(c==null)return;if(c.withdraw(s.getUsername())){s.getRegisteredCourses().remove(c.getCourseID());data.save();msg("Course withdrawn.");}else msg("You are not registered in this course.");}
    static void myCourses(Student s){StringBuilder b=new StringBuilder();for(String id:s.getRegisteredCourses()){Course c=data.findCourse(id);if(c!=null)b.append(c.getCourseID()).append(" - ").append(c.getCourseName()).append("\n");}showText("My Courses",b.toString());}
    static void accountSettings(Student s){String[] o={"Change Username","Change Password"};String c=(String)JOptionPane.showInputDialog(frame,"Choose an action","Account Settings",JOptionPane.PLAIN_MESSAGE,null,o,o[0]);if(c==null)return;if(c.startsWith("Change Username")){String u=ask("New username:");if(u==null)return;u=u.trim();if(u.isEmpty())return;Student x=data.findUsername(u);if(x!=null&&x!=s){msg("Username already exists. Please choose another username.");return;}for(Course cr:data.courses())if(cr.getStudentUsernames().remove(s.getUsername()))cr.getStudentUsernames().add(u);s.setUsername(u);data.save();msg("Username changed successfully.");}else{JPasswordField a=new JPasswordField(),b=new JPasswordField();JPanel p=new JPanel(new GridLayout(2,2,8,8));p.add(label("New password"));p.add(a);p.add(label("Confirm password"));p.add(b);if(JOptionPane.showConfirmDialog(frame,p,"Change Password",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){String x=new String(a.getPassword()),y=new String(b.getPassword());if(x.isEmpty()||!x.equals(y)){msg("Passwords do not match.");return;}s.setPassword(x);data.save();msg("Password changed successfully.");}}}
    static void showText(String title,String text){JTextArea a=new JTextArea(text);a.setFont(normal);a.setEditable(false);a.setLineWrap(true);a.setWrapStyleWord(true);JScrollPane sp=new JScrollPane(a);sp.setPreferredSize(new Dimension(650,420));JOptionPane.showMessageDialog(frame,sp,title,JOptionPane.INFORMATION_MESSAGE);}
}
